"""Complete canonical 2x2 games and experiment infrastructure."""

from .base import Payoff, Player, Profile, SymmetricTwoByTwoGame, format_payoff_matrix
from .chicken import ChickenParameters, chicken, chicken_threshold_report
from .prisoners_dilemma import PrisonersDilemmaParameters, prisoners_dilemma, prisoners_dilemma_threshold_report
from .scenarios import AUTONOMOUS_ESCALATION, FRONTIER_DEPLOYMENT_RACE, SCENARIOS, CanonicalScenario, scenario_from_id
from .simulation import (
    CompetitiveStrategy,
    CooperativeStrategy,
    ExpectedUtilityStrategy,
    GameStrategy,
    GrimTriggerStrategy,
    MatchResult,
    MixedNashStrategy,
    QuantalResponseStrategy,
    RandomStrategy,
    RoundContext,
    RoundResult,
    ThresholdSweepPoint,
    TitForTatStrategy,
    TournamentResult,
    default_strategies,
    play_match,
    round_robin,
    threshold_sweep,
)
from .thresholds import InterventionPolicy, UtilityThresholdReport
from .uncertainty import (
    DiscreteDistribution,
    PayoffState,
    UncertainPayoffGame,
    WeightedOutcome,
    payoff_states,
)

__all__ = [
    "AUTONOMOUS_ESCALATION",
    "FRONTIER_DEPLOYMENT_RACE",
    "SCENARIOS",
    "CanonicalScenario",
    "ChickenParameters",
    "CompetitiveStrategy",
    "CooperativeStrategy",
    "ExpectedUtilityStrategy",
    "GameStrategy",
    "GrimTriggerStrategy",
    "InterventionPolicy",
    "DiscreteDistribution",
    "MatchResult",
    "MixedNashStrategy",
    "Payoff",
    "PayoffState",
    "Player",
    "PrisonersDilemmaParameters",
    "Profile",
    "QuantalResponseStrategy",
    "RandomStrategy",
    "RoundContext",
    "RoundResult",
    "SymmetricTwoByTwoGame",
    "ThresholdSweepPoint",
    "TitForTatStrategy",
    "TournamentResult",
    "UncertainPayoffGame",
    "UtilityThresholdReport",
    "WeightedOutcome",
    "chicken",
    "chicken_threshold_report",
    "default_strategies",
    "format_payoff_matrix",
    "play_match",
    "payoff_states",
    "prisoners_dilemma",
    "prisoners_dilemma_threshold_report",
    "round_robin",
    "scenario_from_id",
    "threshold_sweep",
]
